version: '3.7'

services:
  database:
    image: postgres
    container_name: database_baduk
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=baduk_test
    volumes:
      - pgdata:/data/POSTGRES_DB

volumes:
  pgdata:
    driver: local